"""
FuzzForge: Business Code Agent.

Responsible for generating business code (src/main/kotlin/):
  1. GeneratorConfig.kt
  2. Generator.kt
  3. Translator.kt
  4. Runner.kt
  5. RunConfig.kt
  6. App.kt (CLI)
  7. Root build.gradle.kts

This agent NEVER touches tree/ files.
"""

from pathlib import Path
from typing import Any


def _pkg(parts: list[str]) -> str:
    return "package " + ".".join(parts)


def _pn(design: dict) -> str:
    """Get project name for use in class names."""
    return design.get("project_name", "my-fuzzer").capitalize().replace("-", "").replace("_", "")


def gen_generator_config(design: dict[str, Any], output_dir: str) -> str:
    """Generate GeneratorConfig.kt."""
    pkg = "com.fuzzforge"
    fields = design.get("generator_config", {}).get("fields", [])
    field_lines2 = []
    for f in fields:
        field_lines2.append(f"    val {f['name']}: {f['type']} = {f.get('default_value', '')},")
    content = f"""\
{_pkg([pkg, "generator"])}

data class GeneratorConfig(
    val seed: Long = System.currentTimeMillis(),
{chr(10).join(field_lines2)}
) {{
    companion object {{
        val default = GeneratorConfig()
    }}
}}
"""
    path = Path(output_dir) / "src" / "main" / "kotlin" / "com" / "fuzzforge" / "config" / "GeneratorConfig.kt"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return str(path)


def gen_run_config(output_dir: str) -> str:
    """Generate RunConfig.kt."""
    content = """\
package com.fuzzforge.config

import com.fuzzforge.generator.GeneratorConfig

data class RunConfig(
    val outputDir: String = "./reports",
    val logLevel: String = "info",
    val workers: Int = 4,
    val batchSize: Int = 200,
    val runTimeoutSeconds: Int = 120,
    val generatorConfig: GeneratorConfig = GeneratorConfig.default,
) {
    companion object {
        val default = RunConfig()
    }
}
"""
    path = Path(output_dir) / "src" / "main" / "kotlin" / "com" / "fuzzforge" / "config" / "RunConfig.kt"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return str(path)


def gen_generator(design: dict[str, Any], output_dir: str) -> str:
    """Generate Generator.kt.

    Key design: uses buildProgram() from auto-generated builders.
    Never references UirVisitor or UirTransformer directly.
    """
    base = _pn(design)
    content = f"""\
package com.fuzzforge.generator

import kotlin.random.Random
import com.fuzzforge.ir.UirProgram
import com.fuzzforge.ir.builder.buildProgram

class {base}Generator(
    private val config: GeneratorConfig = GeneratorConfig.default,
) {{
    private val random: Random = Random.Default

    fun generate(): UirProgram {{
        return buildProgram()
    }}
}}
"""
    path = Path(output_dir) / "src" / "main" / "kotlin" / "com" / "fuzzforge" / "generator" / "Generator.kt"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return str(path)


def gen_translator(design: dict[str, Any], output_dir: str) -> str:
    """Generate Translator.kt."""
    base = _pn(design)
    content = f"""\
package com.fuzzforge.translator

import com.fuzzforge.ir.UirProgram

interface FuzzForgeTranslator<R> {{
    fun translate(program: UirProgram): R
}}

class {base}Translator : FuzzForgeTranslator<String> {{
    override fun translate(program: UirProgram): String {{
        return "Generated by FuzzForge"
    }}
}}
"""
    path = Path(output_dir) / "src" / "main" / "kotlin" / "com" / "fuzzforge" / "translator" / "Translator.kt"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return str(path)


def gen_runner(design: dict[str, Any], output_dir: str) -> str:
    """Generate Runner.kt."""
    base = _pn(design)
    content = f"""\
package com.fuzzforge.runner

import com.fuzzforge.generator.{base}Generator
import com.fuzzforge.translator.{base}Translator
import com.fuzzforge.config.RunConfig
import kotlinx.coroutines.*
import java.io.File

data class RunResult(val success: Boolean, val stdout: String, val stderr: String, val exitCode: Int, val durationMs: Long)

class {base}Runner(
    private val config: RunConfig,
) {{
    private val generator = {base}Generator(config.generatorConfig)
    private val translator = {base}Translator()

    suspend fun runSingle(seed: Long? = null): RunResult {{
        val program = if (seed != null) {{
            {base}Generator(config.generatorConfig.copy(seed = seed)).generate()
        }} else {{
            generator.generate()
        }}
        val code = translator.translate(program)
        return RunResult(success = true, stdout = code, stderr = "", exitCode = 0, durationMs = 0)
    }}

    suspend fun runBatch(count: Int): List<RunResult> = coroutineScope {{
        (0 until count).map {{ runSingle() }}
    }}
}}
"""
    path = Path(output_dir) / "src" / "main" / "kotlin" / "com" / "fuzzforge" / "runner" / "Runner.kt"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return str(path)


def gen_app(design: dict[str, Any], output_dir: str) -> str:
    """Generate App.kt (CLI)."""
    pn = design.get("project_name", "my-fuzzer").lower()
    base = _pn(design)
    content = f"""\
package com.fuzzforge.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.context
import com.github.ajalt.clikt.core.subcommands
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.types.int
import com.github.ajalt.clikt.output.MordantHelpFormatter
import com.fuzzforge.config.RunConfig
import com.fuzzforge.generator.{base}Generator
import com.fuzzforge.runner.{base}Runner
import kotlinx.coroutines.runBlocking

class {base}Command : CliktCommand(
    name = "{pn}",
    help = "{design.get('description', 'Fuzzer generated by FuzzForge')}",
) {{
    init {{
        context {{ helpFormatter = {{ MordantHelpFormatter(it, showDefaultValues = true) }} }}
        subcommands(RunCommand(), GenerateCommand())
    }}
    override fun run() {{
        echo("{base} — Fuzzer")
        echo("Run with a subcommand: run or generate")
    }}
}}

class RunCommand : CliktCommand(name = "run", help = "Run fuzzing campaign") {{
    val count: Int by option("-n").int().default(10)
    val output: String by option("-o").default("./reports")
    override fun run() {{
        echo("Running campaign: $count programs")
        val config = RunConfig(outputDir = output)
        val runner = {base}Runner(config)
        runBlocking {{
            val results = runner.runBatch(count)
            echo("Done: ${{results.count {{ it.success }}}}/$count succeeded")
        }}
    }}
}}

class GenerateCommand : CliktCommand(name = "generate", help = "Generate programs only") {{
    val count: Int by option("-n").int().default(5)
    override fun run() {{
        val generator = {base}Generator()
        for (i in 0 until count) {{
            generator.generate()
            echo("Generated ${{i + 1}}")
        }}
    }}
}}

fun main(args: Array<String>) = {base}Command().main(args)
"""
    path = Path(output_dir) / "src" / "main" / "kotlin" / "com" / "fuzzforge" / "cli" / "App.kt"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return str(path)


def gen_root_build(design: dict[str, Any], output_dir: str) -> str:
    """Generate root build.gradle.kts."""
    base = _pn(design)
    content = f"""\
plugins {{ id("java"); kotlin("jvm"); application; kotlin("plugin.serialization") version "2.4.0" }}
group = "com.fuzzforge"; version = "1.0-SNAPSHOT"
repositories {{ mavenCentral() }}
kotlin {{ jvmToolchain(17) }}
dependencies {{
    implementation(kotlin("stdlib"))
    implementation(project(":tree"))
    implementation("org.yaml:snakeyaml:2.0")
    implementation("com.github.ajalt.clikt:clikt-jvm:4.2.2")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0")
    implementation("io.github.oshai:kotlin-logging-jvm:7.0.3")
    implementation("ch.qos.logback:logback-classic:1.5.18")
}}
application {{ mainClass = "com.fuzzforge.cli.{base}CommandKt" }}
sourceSets.main {{ kotlin.srcDir("src/main/kotlin") }}
tasks.test {{ useJUnitPlatform() }}
"""
    path = Path(output_dir) / "build.gradle.kts"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return str(path)


def generate_business_code(design: dict[str, Any], output_dir: str) -> list[str]:
    """Generate all business code files. Returns list of generated file paths."""
    paths = []
    paths.append(gen_generator_config(design, output_dir))
    paths.append(gen_run_config(output_dir))
    paths.append(gen_generator(design, output_dir))
    paths.append(gen_translator(design, output_dir))
    paths.append(gen_runner(design, output_dir))
    paths.append(gen_app(design, output_dir))
    paths.append(gen_root_build(design, output_dir))

    # .gitignore
    (Path(output_dir) / ".gitignore").write_text(".gradle/\nbuild/\nout/\ngen/\n")

    # README
    (Path(output_dir) / "README.md").write_text(f"# {design.get('project_name', 'fuzzer')}\n\nFuzzer generated by FuzzForge.\n")

    return paths