"""
FuzzForge: healer — autonomous build-fix engine.
Scans build errors, calls real LLM (GLM-5.2 via SF) for patches, applies fixes, retries.
"""

import json
import os
import subprocess
import urllib.request
from pathlib import Path
from typing import Any

from fuzzforge.runner import run_gradle, diagnose_failure
from fuzzforge.tree_api import build_fix_guidelines

# Read LLM config from Hermes config
def _load_sf_config():
    import yaml
    with open(os.path.expanduser("~/.hermes/config.yaml")) as f:
        cfg = yaml.safe_load(f)
    # Try custom_providers first
    for prov in cfg.get("custom_providers", []):
        if prov.get("name") == "sf":
            return prov.get("api_key"), prov.get("base_url", "https://api.sfkey.cn/v1"), prov.get("model", "glm-5.2")
    # Fallback to model config
    m = cfg.get("model", {})
    return m.get("api_key"), m.get("base_url", "https://api.sfkey.cn/v1"), m.get("default", "glm-5.2")

SF_API_KEY, SF_BASE_URL, SF_MODEL = _load_sf_config()


def call_llm_for_fix(prompt: str) -> str:
    """Call the real LLM (GLM-5.2 via SF) to generate fix patches."""
    data = json.dumps({
        "model": SF_MODEL,
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are a Kotlin compiler fixer. A fuzzer project generated by FuzzForge has build errors. "
                    "Your job is to analyze the errors and output patches to fix ONLY the business code.\n\n"
                    "CRITICAL RULES:\n"
                    "1. NEVER patch files under 'tree/' — they are auto-generated or boilerplate.\n"
                    "2. NEVER patch files under 'tree/gen/' — they are regenerated from TreeBuilder.kt.\n"
                    "3. ONLY patch files under 'src/main/kotlin/com/fuzzforge/'.\n"
                    "4. NEVER create new files. NEVER delete files.\n"
                    "5. Each patch replaces one unique string with another. Include enough context (3-5 lines).\n"
                    "6. Fix missing imports: if code references UirXxx but only Xxx is imported, add the import.\n"
                    "7. Fix type name mismatches: business code must use the full Uir-prefixed type name.\n"
                    "8. Fix references to non-existent properties like program.graphs.\n"
                    "9. Only output valid JSON, no markdown fences, no extra text.\n\n"
                    "Output format:\n"
                    "[\n"
                    '  {\n'
                    '    "file_path": "relative/path/from/project/root/Filename.kt",\n'
                    '    "old_string": "exact text to find and replace",\n'
                    '    "new_string": "replacement text"\n'
                    '  }\n'
                    "]\n"
                ),
            },
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.1,
    }).encode()

    req = urllib.request.Request(
        f"{SF_BASE_URL}/chat/completions",
        data=data,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {SF_API_KEY}",
        },
    )

    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            result = json.loads(resp.read().decode())
            raw = result["choices"][0]["message"]["content"]
            return raw
    except Exception as e:
        raise RuntimeError(f"LLM call failed: {e}")


def build_fix_prompt(
    project_dir: str,
    stderr: str,
    stdout: str,
    design: dict[str, Any],
    max_files: int = 5,
) -> str:
    """Build a compact fix prompt with error context and key business code files."""
    lines = []
    lines.append("Build errors (only fix business code, never tree/ files):")
    lines.append(stderr[:3000])
    lines.append("")

    base = Path(project_dir)

    # Only include business code files under src/main/kotlin/
    patterns = [
        "src/main/kotlin/com/fuzzforge/cli/App.kt",
        "src/main/kotlin/com/fuzzforge/generator/*.kt",
        "src/main/kotlin/com/fuzzforge/translator/*.kt",
        "src/main/kotlin/com/fuzzforge/runner/*.kt",
        "src/main/kotlin/com/fuzzforge/config/*.kt",
    ]

    for pattern in patterns:
        for f in sorted(base.glob(pattern)):
            rel = f.relative_to(base)
            lines.append(f"--- {rel} ---")
            lines.append(f.read_text())
            if len(lines) > max_files * 30:
                break

    lines.append("")
    return "\n".join(lines)


def parse_fix_response(raw: str) -> list[dict[str, str]]:
    """Parse LLM fix response into a list of patches."""
    raw = raw.strip()
    if raw.startswith("```"):
        lines = raw.split("\n")
        if lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip().startswith("```"):
            lines = lines[:-1]
        raw = "\n".join(lines)

    # Try to find complete JSON array — handle truncated responses
    # Find the last complete patch object
    try:
        patches = json.loads(raw)
        if isinstance(patches, dict):
            for v in patches.values():
                if isinstance(v, list):
                    patches = v
                    break
        if not isinstance(patches, list):
            return []
        return patches
    except json.JSONDecodeError:
        # Try to find the last complete object before truncation
        # Find the innermost complete bracket
        depth = 0
        last_complete = -1
        for i, ch in enumerate(raw):
            if ch == '[':
                depth += 1
            elif ch == ']':
                depth -= 1
                if depth == 0:
                    last_complete = i + 1
        if last_complete > 0:
            try:
                patches = json.loads(raw[:last_complete])
                if isinstance(patches, list):
                    return patches
            except json.JSONDecodeError:
                pass
        return []


def apply_patches(project_dir: str, patches: list[dict[str, str]]) -> list[str]:
    """Apply a list of patches to the project."""
    applied = []
    base = Path(project_dir)

    for patch in patches:
        file_path = patch.get("file_path", "")
        old_str = patch.get("old_string", "")
        new_str = patch.get("new_string", "")
        if not file_path:
            continue

        full_path = base / file_path

        # Safety: NEVER patch tree/ files
        if file_path.startswith("tree/"):
            applied.append(f"REJECTED {file_path} — tree/ files are not business code")
            continue

        # Reject file creation/deletion — the LLM should not do this
        if old_str in ("__FILE_MISSING__", "__FILE_DELETE__"):
            applied.append(f"REJECTED {file_path} ({old_str}) — no file creation/deletion allowed")
            continue

        if not full_path.exists():
            applied.append(f"SKIPPED {file_path} (not found)")
            continue

        content = full_path.read_text()
        if old_str not in content:
            applied.append(f"SKIPPED {file_path} (no match)")
            continue

        new_content = content.replace(old_str, new_str, 1)
        full_path.write_text(new_content)
        applied.append(f"PATCHED {file_path}")

    return applied


def fix_and_rebuild(
    project_dir: str,
    design: dict[str, Any],
    llm_cmd: str | None = None,
    max_iterations: int = 5,
) -> dict[str, Any]:
    """Auto-fix loop: build -> diagnose -> fix via real LLM -> rebuild."""
    print(f"\n{'='*60}")
    print(f"  Auto-Fix Loop: max {max_iterations} iterations")
    print(f"{'='*60}")

    for iteration in range(1, max_iterations + 1):
        print(f"\n  --- Iteration {iteration}/{max_iterations} ---")

        result = run_gradle(project_dir, "compileKotlin", timeout=300)
        if result["success"]:
            print(f"  Build succeeded on iteration {iteration}!")
            return {"success": True, "iterations": iteration, "build_result": result}

        print(f"  Build failed (exit code {result['return_code']})")
        issues = diagnose_failure(result)
        for issue in issues:
            print(f"    - {issue}")

        prompt = build_fix_prompt(project_dir, result["stderr"], result["stdout"], design)

        try:
            print(f"  Calling GLM-5.2 for fixes...")
            raw = call_llm_for_fix(prompt)
            patches = parse_fix_response(raw)
            if not patches:
                print(f"  LLM returned no valid patches")
                print(f"  Raw response: {raw[:500]}")
                continue

            print(f"  LLM returned {len(patches)} patch(es)")
            applied = apply_patches(project_dir, patches)
            for a in applied:
                print(f"    {a}")

        except Exception as e:
            print(f"  Fix iteration failed: {e}")
            import traceback
            traceback.print_exc()
            continue

    print(f"\n  Auto-fix exhausted after {max_iterations} iterations")
    return {
        "success": False,
        "iterations": max_iterations,
        "build_result": run_gradle(project_dir, "compileKotlin", timeout=300),
    }