"""
FuzzForge: Knowledge Index.

This module is a thin index that maps domain names to skill files.
Detailed knowledge is stored in layered skills under ~/.hermes/skills/mlops/.

Agents should load the relevant skill when they need domain-specific knowledge:
  skill_view(name='fuzzforge-cpp-translator')
  skill_view(name='fuzzforge-cpp-generator')
  skill_view(name='fuzzforge-classifier')
  skill_view(name='fuzzforge-ir-design')
"""

import os
from pathlib import Path
from typing import Any


def build_knowledge_context(mode: str) -> str:
    """Build a compact knowledge context string for the given mode.

    This is a thin index — returns just the essential structure and
    pointers to the skill files for detailed knowledge.
    """
    lines = []
    lines.append("=== FuzzForge Knowledge Index ===")
    lines.append(f"Mode: {mode}")
    lines.append("")
    lines.append("Available skills (load with skill_view):")
    lines.append("  - fuzzforge-cpp-generator: Builder API, class/function generation patterns")
    lines.append("  - fuzzforge-cpp-translator: C++ visitor patterns, syntax rules, semantic constraints")
    lines.append("  - fuzzforge-classifier: Error classification patterns for C++ compilation")
    lines.append("  - fuzzforge-ir-design: IR element hierarchy, root element rules, naming")
    lines.append("")
    lines.append("=== Essential Rules (always applicable) ===")
    lines.append("")
    lines.append("Root element: auto-generated by TreeBuilder as rootElement.")
    lines.append("  Do NOT include a separate 'element' entry in tree_builder_elements.")
    lines.append("")
    lines.append("Uir prefix: all generated types get the 'Uir' prefix.")
    lines.append("  Business code must use full type names (UirProgram, UirClassDeclaration, etc.).")
    lines.append("")
    lines.append("Builder API: use buildProgram, buildClassDeclaration, buildFunctionDeclaration, etc.")
    lines.append("  from com.fuzzforge.ir.builder.* - NOT impl classes directly.")
    lines.append("")
    lines.append("acceptChildren: empty in impl classes. Directly access child fields.")
    lines.append("")
    lines.append("Element names: avoid Kotlin keywords (If/For/Return -> IfStmt/ForStmt/ReturnStmt).")
    lines.append("")
    lines.append("Main class: App.kt -> JVM class is AppKt, not {base}CommandKt.")
    lines.append("")
    lines.append("GeneratorConfig: package com.fuzzforge.generator, file in generator/ directory.")
    lines.append("")
    return "\n".join(lines)


def _get_knowledge_path() -> str:
    """Get the path to the knowledge skills directory."""
    return str(Path.home() / ".hermes" / "skills" / "mlops")


def get_skill_content(name: str) -> str:
    """Read a skill file directly (fallback if skill_view is unavailable)."""
    path = Path.home() / ".hermes" / "skills" / "mlops" / name / "SKILL.md"
    if path.exists():
        return path.read_text()
    return f"Skill '{name}' not found."


# Keep the old dict-based API for backward compatibility
def get_knowledge(mode: str) -> dict[str, Any]:
    """Legacy: return the knowledge dict for a given mode."""
    return {
        "ir_mode": mode,
        "knowledge_index": build_knowledge_context(mode),
        "note": "Detailed knowledge is in skill files. Use skill_view() to load them.",
    }