"""
FuzzForge: Tree Generator API Explainer.

Documents the tree-generator-common library API surface so that
LLM agents know what they CAN and CANNOT do with the tree-generator
infrastructure.

Key insight: The tree-generator uses a meta-model (AbstractElementConfigurator)
to auto-generate IR source code. The generated code should NEVER be edited
directly. The meta-model (TreeBuilder.kt) should only be modified by codegen,
not by the fix LLM.
"""

TREE_GENERATOR_KNOWLEDGE = {
    "version": "1.0",
    "library": "org.jetbrains.kotlin:kotlin-generators-tree:1.9.0 (via tree-generator-common.jar)",
    "architecture": {
        "meta_model": "TreeBuilder.kt — declares IR elements via AbstractElementConfigurator DSL",
        "code_generation": "Running generateTree produces tree/gen/ with all interfaces, implementations, visitors, transformers, builders",
        "auto_generated": "tree/gen/ — DO NOT EDIT, regenerated from TreeBuilder.kt",
        "boilerplate": "tree/tree-generator/src/ — the tree-generator runtime (model/, printer/, types.kt, etc.)",
    },
    "do_not_modify": [
        "tree/gen/ — auto-generated IR code, regenerated from TreeBuilder.kt",
        "tree/tree-generator/src/ — tree-generator boilerplate runtime, not user code",
        "tree/src/main/kotlin/.../ir/visitors/ — auto-generated visitor/transformer classes",
        "tree/src/main/kotlin/.../ir/impl/ — auto-generated implementation classes",
        "tree/src/main/kotlin/.../ir/builder/ — auto-generated builder classes",
        "tree/src/main/kotlin/.../ir/types/ — auto-generated type system classes",
    ],
    "can_modify": [
        "tree/src/main/kotlin/.../ir/OpKind.kt — hand-written enum",
        "tree/src/main/kotlin/.../ir/TypeKind.kt — hand-written enum",
        "tree/src/main/kotlin/.../ir/AttrKind.kt — hand-written enum",
        "tree/src/main/kotlin/.../ir/DimKind.kt — hand-written enum",
        "tree/src/main/kotlin/.../ir/BlockKind.kt — hand-written enum",
        "tree/src/main/kotlin/.../ir/ClassKind.kt — hand-written enum",
        "tree/src/main/kotlin/.../ir/Language.kt — hand-written enum",
        "src/main/kotlin/ — all business code (generator, translator, runner, config, CLI)",
    ],
    "tree_builder_rules": [
        "TreeBuilder.kt is generated by codegen.py — do NOT modify it directly",
        "If TreeBuilder.kt has errors, fix codegen.py, not the generated file",
        "Root element must be named 'Element' with hasAcceptChildren=true and hasTransformChildren=true",
        "Elements with isChild=true participate in Visitor/Transformer traversal",
        "Elements with isChild=false are value properties (not traversed)",
        "Enum fields must have isChild=false",
        "List fields use list_base_type to specify element type",
        "Parent references model inheritance (e.g. TensorType parent=Type)",
    ],
    "common_build_errors": [
        {
            "error": "Unresolved reference 'model'",
            "cause": "TreeBuilder.kt imports com.fuzzforge.tree.generator.model.* but the model classes are in the tree-generator boilerplate",
            "fix": "This is a tree-generator infrastructure issue. Do NOT try to fix TreeBuilder.kt. The boilerplate must be copied correctly.",
        },
        {
            "error": "'accept' in 'UirElement' is final",
            "cause": "UirElement was generated as abstract class instead of interface. This means the root element in TreeBuilder.kt has kind=AbstractClass instead of Interface.",
            "fix": "This is a codegen issue. The root element definition missing 'kind = ImplementationKind.Interface' is a codegen bug.",
        },
        {
            "error": "Unresolved reference 'UirVisitor'",
            "cause": "Business code imports from wrong package.",
            "fix": "Fix the import statement in the business code file.",
        },
        {
            "error": "Syntax error: Expecting comma or ')'",
            "cause": "Kotlin constructor parameters missing trailing commas.",
            "fix": "Add trailing commas to constructor parameter list.",
        },
    ],
}


def print_tree_generator_api():
    """Print the tree-generator API documentation for the Agent."""
    print("=" * 60)
    print("Tree Generator API Reference")
    print("=" * 60)
    print()
    print("Architecture:")
    for k, v in TREE_GENERATOR_KNOWLEDGE["architecture"].items():
        print(f"  {k}: {v}")
    print()
    print("DO NOT MODIFY:")
    for item in TREE_GENERATOR_KNOWLEDGE["do_not_modify"]:
        print(f"  ❌ {item}")
    print()
    print("CAN MODIFY:")
    for item in TREE_GENERATOR_KNOWLEDGE["can_modify"]:
        print(f"  ✅ {item}")
    print()
    print("TreeBuilder Rules:")
    for rule in TREE_GENERATOR_KNOWLEDGE["tree_builder_rules"]:
        print(f"  • {rule}")
    print()
    print("Common Build Errors:")
    for err in TREE_GENERATOR_KNOWLEDGE["common_build_errors"]:
        print(f"  • {err['error']}")
        print(f"    Cause: {err['cause']}")
        print(f"    Fix: {err['fix']}")
        print()


def build_fix_guidelines() -> str:
    """Build a compact text for the LLM fix prompt about what to fix and what not to."""
    lines = [
        "## FIX GUIDELINES",
        "",
        "### Files you CAN patch (business code only):",
        "  - src/main/kotlin/com/fuzzforge/**/*.kt",
        "",
        "### Files you MUST NOT patch (tree infrastructure):",
        "  - tree/gen/ — auto-generated, DO NOT EDIT",
        "  - tree/tree-generator/ — boilerplate runtime",
        "  - tree/src/main/kotlin/.../ir/visitors/ — auto-generated",
        "  - tree/src/main/kotlin/.../ir/impl/ — auto-generated",
        "  - tree/src/main/kotlin/.../ir/builder/ — auto-generated",
        "  - tree/src/main/kotlin/.../ir/types/ — auto-generated",
        "",
        "### If you see errors in tree/ files, do NOT try to patch them.",
        "### Instead, patch the corresponding business code that references them.",
        "",
        "### Common Kotlin fixes:",
        "  - Add missing imports",
        "  - Fix type names (e.g. UirProgram vs Program)",
        "  - Add trailing commas to constructor parameter lists",
        "  - Remove references to non-existent properties (program.graphs, etc.)",
    ]
    return "\n".join(lines)